apiVersion: v2
appVersion: 2.10.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://keitaro-charts.storage.googleapis.com
  version: 18.12.1
- condition: solr.enabled
  name: solr
  repository: https://keitaro-charts.storage.googleapis.com
  version: 8.7.1
- condition: postgresql.enabled
  name: postgresql
  repository: https://keitaro-charts.storage.googleapis.com
  version: 14.0.1
- condition: datapusher.enabled
  name: datapusher
  repository: https://keitaro-charts.storage.googleapis.com
  version: 1.0.0
description: CKAN Helm chart
name: ckan
type: application
version: v3.4.0
