apiVersion: v2
appVersion: 2.11.3
dependencies:
- condition: redis.enabled
  name: redis
  repository: https://keitaro-charts.storage.googleapis.com
  version: 23.0.2
- condition: solr.enabled
  name: solr
  repository: https://keitaro-charts.storage.googleapis.com
  version: 9.6.10
- condition: postgresql.enabled
  name: postgresql
  repository: https://keitaro-charts.storage.googleapis.com
  version: 16.7.27
description: CKAN Helm chart
name: ckan
type: application
version: v4.0.0
