apiVersion: v2
name: ckan
description: CKAN Helm chart

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
version: 1.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
appVersion: 2.9.2

# Dependencies
dependencies:
  - name: redis 
    version: 12.2.3
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: solr
    version: 1.4.0
    repository: "https://charts.helm.sh/incubator"
    condition: solr.enabled
  - name: postgresql
    version: 10.2.0
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: datapusher
    version: 1.0.0
    repository: "https://keitaro-charts.storage.googleapis.com"
    condition: datapusher.enabled

