{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: ckansysadminapitoken
type: Opaque
stringData:
  sysadminApiToken: {{ .Values.ckan.sysadminApiToken }}
{{- end }}
