{{- if index .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: ckan-virtual-service
spec:
  hosts:
  - {{ index .Values.istio.host }}
  gateways:
  - {{ index .Values.istio "gateway-name" }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: ckan
    timeout: 300000s
{{- end }}
