{{- if .Values.istio.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.istio.certificate.name }}
  namespace: istio-system
spec:
  secretName: {{ .Values.istio.secret.name }} 
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - {{ .Values.istio.host }}
  issuerRef:
    name: {{ .Values.istio.issuer.name }}
    kind: Issuer
{{- end }}

