apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: test-user
spec:
  host: ckan.ckan.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpCookie:
          name: user
          ttl: 0s