{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ index .Values.istio "gateway-name" }}
spec:
  selector:
    app: {{ index .Values.istio "app-selector" }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: {{ .Values.istio.redirect }}
    hosts:
    - {{ .Values.istio.host }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .Values.istio.secret.name }}
    hosts:
    - {{ .Values.istio.host }}
{{- end }}
