{{- if .Values.ckan.psql.initialize -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: psql-init
spec:
  template:
    spec:
      volumes:
        - name: psql-init-configmap
          configMap:
            name: psql-init-configmap
      containers:
      - name: psql-init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: PSQL_MASTER
          value: {{ .Values.ckan.psql.masterUser }}
        - name: PSQL_PASSWD
          value: {{ .Values.ckan.psql.masterPassword }}
        - name: PSQL_DB
          value: {{ .Values.ckan.psql.masterDatabase }}
        - name: CKAN_SOLR_URL
          value: {{ .Values.ckan.solr }}
        - name: CKAN_SQLALCHEMY_URL
          valueFrom:
            secretKeyRef:
              name: ckancredentials
              key: ckanSqlAlchemyUrl
        - name: CKAN_DATASTORE_WRITE_URL
          valueFrom:
            secretKeyRef:
              name: ckancredentials
              key: ckanDatastoreWriteUrl
        - name: CKAN_DATASTORE_READ_URL
          valueFrom:
            secretKeyRef:
              name: ckancredentials
              key: ckanDatastoreReadUrl
        command: ["python"]
        args: ["/srv/psql-init/psql-init.py"]
        volumeMounts:
        - name: psql-init-configmap
          mountPath: /srv/psql-init
      restartPolicy: Never
  backoffLimit: 2
{{- end }}
