{{- if .Values.solr.initialize.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: solr-init-{{ randAlphaNum 5 | lower }}
spec:
  template:
    spec:
      securityContext:
        {{- toYaml $.Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: solr-init-configmap
          configMap:
            name: solr-init-configmap
        - name: solr-configset-configmap
          configMap:
            name: solr-configset-configmap
      containers:
        - name: solr-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml $.Values.securityContext | nindent 12 }}
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          resources: 
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          env:
            - name: CKAN_SOLR_URL
              value: {{ .Values.ckan.solr }}
            - name: SOLR_ADMIN_USERNAME
              value: {{ .Values.solr.auth.adminUsername }}
            - name: SOLR_ADMIN_PASSWORD
              value: {{ .Values.solr.auth.adminPassword }}
            - name: CKAN_SOLR_INIT_NUMSHARDS
              value: "{{ .Values.solr.initialize.numShards }}"
            - name: CKAN_SOLR_INIT_REPLICATIONFACTOR
              value: "{{ .Values.solr.initialize.replicationFactor }}"
            - name: CKAN_SOLR_INIT_MAXSHARDSPERNODE
              value: "{{ .Values.solr.initialize.maxShardsPerNode }}"
            - name: CKAN_SOLR_INIT_CONFIGSETNAME
              value: "{{ .Values.solr.initialize.configsetName }}"
          command: ["python"]
          args: ["/app/solr-init/solr-init.py"]
          {{- if eq .Values.solr.initialize.container_debug "true" }}
          command: ["sleep"]
          args: ["infinity"]
          {{- end }}
          volumeMounts:
            - name: solr-init-configmap
              mountPath: /app/solr-init
            - name: solr-configset-configmap
              mountPath: /app/solr-configset
      restartPolicy: Never
  backoffLimit: 1
{{- end }}
